# 使用官方的Python基础镜像
FROM python:3.9-buster

# 设置工作目录
WORKDIR /app

# 更新包管理器并安装依赖项
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gcc \
    python3-dev \
    libmysqlclient-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# 将requirements.txt文件复制到工作目录
COPY requirements.txt .

# 安装Python依赖项
RUN pip install --no-cache-dir -r requirements.txt
